In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf


In [ ]:
from dataclasses import dataclass
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler,StandardScaler
from keras.preprocessing.sequence import TimeseriesGenerator

from tensorflow.keras.metrics import MeanSquaredError, MeanAbsoluteError, RootMeanSquaredError


In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/model.csv")

In [ ]:
df.head()

time                            _start  \
0  2023-02-19 12:16:58.020000+00:00  2023-02-19 12:04:53.069418+00:00   
1  2023-02-19 12:18:03.814000+00:00  2023-02-19 12:04:53.069418+00:00   
2  2023-02-19 12:21:05.619000+00:00  2023-02-19 12:04:53.069418+00:00   
3  2023-02-19 12:24:38.413000+00:00  2023-02-19 12:04:53.069418+00:00   
4  2023-02-19 12:26:32.840000+00:00  2023-02-19 12:04:53.069418+00:00   

                              _stop                             _time  \
0  2023-02-20 12:04:53.069418+00:00  2023-02-19 12:16:58.020000+00:00   
1  2023-02-20 12:04:53.069418+00:00  2023-02-19 12:18:03.814000+00:00   
2  2023-02-20 12:04:53.069418+00:00  2023-02-19 12:21:05.619000+00:00   
3  2023-02-20 12:04:53.069418+00:00  2023-02-19 12:24:38.413000+00:00   
4  2023-02-20 12:04:53.069418+00:00  2023-02-19 12:26:32.840000+00:00   

   _field_cdi  _field_depth  _field_dmin  _field_felt  _field_gap  _field_lat  \
0         0.0         29.53      0.01774            0       186.0   38.823666   
1         0.0         75.00      0.00000            0         0.0   59.182600   
2         0.0         10.00      7.51900            0        60.0  -12.767900   
3         0.0        122.20      0.00000            0         0.0   59.859200   
4         0.0          4.45      0.13540            0        89.0   33.271833   

   ...  magType_ml  magType_mwr  magType_mww  net_ak  net_ci  net_hv  net_nc  \
0  ...           0            0            0       0       0       0       1   
1  ...           1            0            0       1       0       0       0   
2  ...           0            0            0       0       0       0       0   
3  ...           1            0            0       1       0       0       0   
4  ...           1            0            0       0       1       0       0   

   net_ok  net_pr  net_us  
0       0       0       0  
1       0       0       0  
2       0       0       1  
3       0       0       0  
4       0       0       0  

[5 rows x 30 columns]

In [ ]:
df=df.sort_values(["time"], ascending= True)

In [ ]:
df

time                            _start  \
0    2023-02-19 12:16:58.020000+00:00  2023-02-19 12:04:53.069418+00:00   
1    2023-02-19 12:18:03.814000+00:00  2023-02-19 12:04:53.069418+00:00   
2    2023-02-19 12:21:05.619000+00:00  2023-02-19 12:04:53.069418+00:00   
3    2023-02-19 12:24:38.413000+00:00  2023-02-19 12:04:53.069418+00:00   
4    2023-02-19 12:26:32.840000+00:00  2023-02-19 12:04:53.069418+00:00   
..                                ...                               ...   
189  2023-02-20 09:11:18.820000+00:00  2023-02-19 12:04:53.069418+00:00   
190  2023-02-20 09:15:40.750000+00:00  2023-02-19 12:04:53.069418+00:00   
191  2023-02-20 09:17:24.280000+00:00  2023-02-19 12:04:53.069418+00:00   
192  2023-02-20 09:28:32.600000+00:00  2023-02-19 12:04:53.069418+00:00   
193  2023-02-20 09:29:40.410000+00:00  2023-02-19 12:04:53.069418+00:00   

                                _stop                             _time  \
0    2023-02-20 12:04:53.069418+00:00  2023-02-19 12:16:58.020000+00:00   
1    2023-02-20 12:04:53.069418+00:00  2023-02-19 12:18:03.814000+00:00   
2    2023-02-20 12:04:53.069418+00:00  2023-02-19 12:21:05.619000+00:00   
3    2023-02-20 12:04:53.069418+00:00  2023-02-19 12:24:38.413000+00:00   
4    2023-02-20 12:04:53.069418+00:00  2023-02-19 12:26:32.840000+00:00   
..                                ...                               ...   
189  2023-02-20 12:04:53.069418+00:00  2023-02-20 09:11:18.820000+00:00   
190  2023-02-20 12:04:53.069418+00:00  2023-02-20 09:15:40.750000+00:00   
191  2023-02-20 12:04:53.069418+00:00  2023-02-20 09:17:24.280000+00:00   
192  2023-02-20 12:04:53.069418+00:00  2023-02-20 09:28:32.600000+00:00   
193  2023-02-20 12:04:53.069418+00:00  2023-02-20 09:29:40.410000+00:00   

     _field_cdi  _field_depth  _field_dmin  _field_felt  _field_gap  \
0           0.0         29.53     0.017740            0       186.0   
1           0.0         75.00     0.000000            0         0.0   
2           0.0         10.00     7.519000            0        60.0   
3           0.0        122.20     0.000000            0         0.0   
4           0.0          4.45     0.135400            0        89.0   
..          ...           ...          ...          ...         ...   
189         0.0          2.25     0.011780            0        86.0   
190         0.0          2.44     0.011440            0        72.0   
191         0.0          2.21     0.011950            0       104.0   
192         0.0          3.03     0.004274            0        65.0   
193         0.0          1.99     0.001892            0        88.0   

     _field_lat  ...  magType_ml  magType_mwr  magType_mww  net_ak  net_ci  \
0     38.823666  ...           0            0            0       0       0   
1     59.182600  ...           1            0            0       1       0   
2    -12.767900  ...           0            0            0       0       0   
3     59.859200  ...           1            0            0       1       0   
4     33.271833  ...           1            0            0       0       1   
..          ...  ...         ...          ...          ...     ...     ...   
189   38.835167  ...           0            0            0       0       0   
190   38.834835  ...           0            0            0       0       0   
191   38.835167  ...           0            0            0       0       0   
192   38.822166  ...           0            0            0       0       0   
193   38.827168  ...           0            0            0       0       0   

     net_hv  net_nc  net_ok  net_pr  net_us  
0         0       1       0       0       0  
1         0       0       0       0       0  
2         0       0       0       0       1  
3         0       0       0       0       0  
4         0       0       0       0       0  
..      ...     ...     ...     ...     ...  
189       0       1       0       0       0  
190       0       1       0       0       0  
191       0       1       0

In [ ]:
df=df.drop("_time",axis=1)

In [ ]:
df=df.drop("time",axis=1)

In [ ]:
df=df.drop("_start",axis=1)

In [ ]:
df= df.drop("_stop",axis=1)

In [ ]:
df.head()

_field_cdi  _field_depth  _field_dmin  _field_felt  _field_gap  _field_lat  \
0         0.0         29.53      0.01774            0       186.0   38.823666   
1         0.0         75.00      0.00000            0         0.0   59.182600   
2         0.0         10.00      7.51900            0        60.0  -12.767900   
3         0.0        122.20      0.00000            0         0.0   59.859200   
4         0.0          4.45      0.13540            0        89.0   33.271833   

   _field_lon  _field_mag  _field_mmi  _field_nst  ...  magType_ml  \
0 -122.812332        1.12         0.0           7  ...           0   
1 -153.193000        1.90         0.0           0  ...           1   
2   66.364900        4.70         0.0          63  ...           0   
3 -153.316400        1.40         0.0           0  ...           1   
4 -116.430667        0.98         0.0          29  ...           1   

   magType_mwr  magType_mww  net_ak  net_ci  net_hv  net_nc  net_ok  net_pr  \
0            0            0       0       0       0       1       0       0   
1            0            0       1       0       0       0       0       0   
2            0            0       0       0       0       0       0       0   
3            0            0       1       0       0       0       0       0   
4            0            0       0       1       0       0       0       0   

   net_us  
0       0  
1       0  
2       1  
3       0  
4       0  

[5 rows x 26 columns]

In [ ]:
df_input=df[[ '_field_mag','_field_cdi', '_field_depth', '_field_dmin', '_field_felt',
       '_field_gap', '_field_lat', '_field_lon', '_field_mmi',
       '_field_nst', '_field_rms', '_field_sig', '_field_tsunami',
       'magType_mb', 'magType_mb_lg', 'magType_md', 'magType_ml',
       'magType_mwr', 'magType_mww', 'net_ak', 'net_ci', 'net_hv', 'net_nc',
       'net_ok', 'net_pr', 'net_us']]

In [ ]:
df_input.head()

_field_mag  _field_cdi  _field_depth  _field_dmin  _field_felt  _field_gap  \
0        1.12         0.0         29.53      0.01774            0       186.0   
1        1.90         0.0         75.00      0.00000            0         0.0   
2        4.70         0.0         10.00      7.51900            0        60.0   
3        1.40         0.0        122.20      0.00000            0         0.0   
4        0.98         0.0          4.45      0.13540            0        89.0   

   _field_lat  _field_lon  _field_mmi  _field_nst  ...  magType_ml  \
0   38.823666 -122.812332         0.0           7  ...           0   
1   59.182600 -153.193000         0.0           0  ...           1   
2  -12.767900   66.364900         0.0          63  ...           0   
3   59.859200 -153.316400         0.0           0  ...           1   
4   33.271833 -116.430667         0.0          29  ...           1   

   magType_mwr  magType_mww  net_ak  net_ci  net_hv  net_nc  net_ok  net_pr  \
0            0            0       0       0       0       1       0       0   
1            0            0       1       0       0       0       0       0   
2            0            0       0       0       0       0       0       0   
3            0            0       1       0       0       0       0       0   
4            0            0       0       1       0       0       0       0   

   net_us  
0       0  
1       0  
2       1  
3       0  
4       0  

[5 rows x 26 columns]

In [ ]:
df_input.describe()

_field_mag  _field_cdi  _field_depth  _field_dmin  _field_felt  \
count  194.000000  194.000000    194.000000   194.000000   194.000000   
mean     1.948299    0.084536     25.316618     0.567000     0.159794   
std      1.346885    0.460421     37.959313     1.832297     1.543911   
min      0.290000    0.000000     -0.750000     0.000000     0.000000   
25%      1.052500    0.000000      2.187500     0.000000     0.000000   
50%      1.500000    0.000000     10.000000     0.011715     0.000000   
75%      2.357500    0.000000     25.427500     0.127125     0.000000   
max      5.300000    3.400000    227.176000    15.997000    21.000000   

       _field_gap  _field_lat  _field_lon  _field_mmi  _field_nst  ...  \
count  194.000000  194.000000  194.000000  194.000000  194.000000  ...   
mean    71.173754   38.130059  -99.165938    0.050015   18.505155  ...   
std     67.028903   20.925663   80.132571    0.425218   21.688145  ...   
min      0.000000  -58.413600 -174.463200    0.000000    0.000000  ...   
25%      0.000000   33.422333 -149.545700    0.000000    0.000000  ...   
50%     70.500000   38.779333 -122.756916    0.000000   13.500000  ...   
75%    103.750000   58.214850 -116.401167    0.000000   26.000000  ...   
max    323.000000   65.126900  172.124600    4.783000  144.000000  ...   

       magType_ml  magType_mwr  magType_mww      net_ak      net_ci  \
count  194.000000   194.000000   194.000000  194.000000  194.000000   
mean     0.525773     0.015464     0.005155    0.293814    0.211340   
std      0.500627     0.123708     0.071796    0.456687    0.409315   
min      0.000000     0.000000     0.000000    0.000000    0.000000   
25%      0.000000     0.000000     0.000000    0.000000    0.000000   
50%      1.000000     0.000000     0.000000    0.000000    0.000000   
75%      1.000000     0.000000     0.000000    1.000000    0.000000   
max      1.000000     1.000000     1.000000    1.000000    1.000000   

           net_hv      net_nc      net_ok      net_pr      net_us  
count  194.000000  194.000000  194.000000  194.000000  194.000000  
mean     0.025773    0.247423    0.005155    0.046392    0.170103  
std      0.158868    0.432631    0.071796    0.210876    0.376695  
min      0.000000    0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    0.000000    0.000000    0.000000  
50%      0.000000    0.000000    0.000000    0.000000    0.000000  
75%      0.000000    0.000000    0.000000    0.000000    0.000000  
max      1.000000    1.000000    1.000000    1.000000    1.000000  

[8 rows x 26 columns]

In [ ]:
scaler= MinMaxScaler()
df_scaled=scaler.fit_transform(df_input)

In [ ]:
df_scaled

array([[0.16566866, 0.        , 0.13285014, ..., 0.        , 0.        ,
        0.        ],
       [0.32135729, 0.        , 0.33234471, ..., 0.        , 0.        ,
        0.        ],
       [0.88023952, 0.        , 0.04716443, ..., 0.        , 0.        ,
        1.        ],
       ...,
       [0.02794411, 0.        , 0.01298667, ..., 0.        , 0.        ,
        0.        ],
       [0.09181637, 0.        , 0.01658433, ..., 0.        , 0.        ,
        0.        ],
       [0.06586826, 0.        , 0.01202145, ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
features= df_scaled

In [ ]:
target=df_scaled[:,0]

In [ ]:
df_scaled[:,0]

array([0.16566866, 0.32135729, 0.88023952, 0.22155689, 0.13772455,
       0.11776447, 0.20758483, 0.16167665, 0.94011976, 0.30139721,
       0.30139721, 0.58083832, 0.24550898, 0.34131737, 0.58283433,
       0.05389222, 0.92015968, 0.38123752, 0.84031936, 0.22155689,
       0.66067864, 0.24151697, 0.        , 0.32135729, 0.14570858,
       0.28143713, 0.94011976, 0.08982036, 0.32135729, 0.68063872,
       0.34131737, 0.05389222, 0.20159681, 0.26147705, 0.1756487 ,
       1.        , 0.18163673, 0.82035928, 0.23752495, 0.249501  ,
       0.15968064, 0.41317365, 0.02994012, 0.00798403, 0.24151697,
       0.08582834, 0.20958084, 0.24151697, 0.15768463, 0.09181637,
       0.24550898, 0.52095808, 0.36127745, 0.16566866, 0.11177645,
       0.38123752, 0.30139721, 0.0499002 , 0.94011976, 0.58083832,
       0.11177645, 0.41117764, 0.1257485 , 0.15768463, 0.07984032,
       0.62075848, 0.14171657, 0.1497006 , 0.24151697, 0.26147705,
       0.92015968, 0.20958084, 0.33133733, 0.        , 0.18363

In [ ]:
TimeseriesGenerator(data=features,targets=target, length=5, sampling_rate=1,batch_size=1 )[0]

(array([[[0.16566866, 0.        , 0.13285014, 0.00110896, 0.        ,
          0.57585139, 0.78708817, 0.14902679, 0.        , 0.04861111,
          0.1796875 , 0.04176334, 0.        , 0.        , 0.        ,
          1.        , 0.        , 0.        , 0.        , 0.        ,
          0.        , 0.        , 1.        , 0.        , 0.        ,
          0.        ],
         [0.32135729, 0.        , 0.33234471, 0.        , 0.        ,
          0.        , 0.9518838 , 0.06137031, 0.        , 0.        ,
          0.234375  , 0.12761021, 0.        , 0.        , 0.        ,
          0.        , 1.        , 0.        , 0.        , 1.        ,
          0.        , 0.        , 0.        , 0.        , 0.        ,
          0.        ]]]), array([0.88023952]))

## train- test split

In [ ]:
x_train, x_test, y_train , y_test = train_test_split(features,target,test_size=0.2, random_state= 42, shuffle= False)

In [ ]:
x_train.shape

(155, 26)

In [ ]:
x_test.shape

(39, 26)

In [ ]:
#creating train generator and test generator

batch_size=1
win_length=5



In [ ]:
train_generator=TimeseriesGenerator(data=x_train,targets=y_train,length=win_length,batch_size=batch_size,sampling_rate=1)
test_generator=TimeseriesGenerator(data=x_test,targets=y_test,length=win_length,batch_size=batch_size,sampling_rate=1)

In [ ]:
train_generator[0]

(array([[[0.16566866, 0.        , 0.13285014, 0.00110896, 0.        ,
          0.57585139, 0.78708817, 0.14902679, 0.        , 0.04861111,
          0.1796875 , 0.04176334, 0.        , 0.        , 0.        ,
          1.        , 0.        , 0.        , 0.        , 0.        ,
          0.        , 0.        , 1.        , 0.        , 0.        ,
          0.        ],
         [0.32135729, 0.        , 0.33234471, 0.        , 0.        ,
          0.        , 0.9518838 , 0.06137031, 0.        , 0.        ,
          0.234375  , 0.12761021, 0.        , 0.        , 0.        ,
          0.        , 1.        , 0.        , 0.        , 1.        ,
          0.        , 0.        , 0.        , 0.        , 0.        ,
          0.        ],
         [0.88023952, 0.        , 0.04716443, 0.47002563, 0.        ,
          0.18575851, 0.36947964, 0.69485452, 0.        , 0.4375    ,
          0.28125   , 0.78654292, 0.        , 1.        , 0.        ,
          0.        , 0.        , 0.        

In [ ]:
train_generator[1]

(array([[[0.32135729, 0.        , 0.33234471, 0.        , 0.        ,
          0.        , 0.9518838 , 0.06137031, 0.        , 0.        ,
          0.234375  , 0.12761021, 0.        , 0.        , 0.        ,
          0.        , 1.        , 0.        , 0.        , 1.        ,
          0.        , 0.        , 0.        , 0.        , 0.        ,
          0.        ],
         [0.88023952, 0.        , 0.04716443, 0.47002563, 0.        ,
          0.18575851, 0.36947964, 0.69485452, 0.        , 0.4375    ,
          0.28125   , 0.78654292, 0.        , 1.        , 0.        ,
          0.        , 0.        , 0.        , 0.        , 0.        ,
          0.        , 0.        , 0.        , 0.        , 0.        ,
          1.        ],
         [0.22155689, 0.        , 0.53942946, 0.        , 0.        ,
          0.        , 0.95736054, 0.06101427, 0.        , 0.        ,
          0.234375  , 0.06728538, 0.        , 0.        , 0.        ,
          0.        , 1.        , 0.        

## model

In [ ]:
num_features= 26 

In [ ]:
model=tf.keras.Sequential()
model.add(tf.keras.layers.LSTM(128,input_shape= (win_length,num_features),return_sequences=True))
model.add(tf.keras.layers.LeakyReLU(alpha=0.5))


model.add(tf.keras.layers.LSTM(128,return_sequences=True))
model.add(tf.keras.layers.LeakyReLU(alpha=0.5))
model.add(tf.keras.layers.Dropout(0.3)) #overfit olup olmadıgını görmek icin 

model.add(tf.keras.layers.LSTM(64,return_sequences=False))
model.add(tf.keras.layers.Dropout(0.3))

model.add(tf.keras.layers.Dense(1))


In [ ]:
model.summary() 


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_6 (LSTM)               (None, 5, 128)            79360     
                                                                 
 leaky_re_lu_4 (LeakyReLU)   (None, 5, 128)            0         
                                                                 
 lstm_7 (LSTM)               (None, 5, 128)            131584    
                                                                 
 leaky_re_lu_5 (LeakyReLU)   (None, 5, 128)            0         
                                                                 
 dropout_4 (Dropout)         (None, 5, 128)            0         
                                                                 
 lstm_8 (LSTM)               (None, 64)                49408     
                                                                 
 dropout_5 (Dropout)         (None, 64)               

In [ ]:
model.compile(loss= tf.losses.MeanSquaredError(),
              optimizer= tf.optimizers.Adam(),
              metrics=[tf.metrics.MeanAbsoluteError(), tf.metrics.RootMeanSquaredError()])

history= model.fit_generator(train_generator, epochs=50, 
                             validation_data= test_generator,
                             shuffle=False)

<ipython-input-161-f1fe904710b7>:5: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  history= model.fit_generator(train_generator, epochs=50,


Epoch 1/50
150/150 [==============================] - 13s 16ms/step - loss: 0.0987 - mean_absolute_error: 0.2459 - val_loss: 0.0345 - val_mean_absolute_error: 0.1540
Epoch 2/50
150/150 [==============================] - 1s 9ms/step - loss: 0.0909 - mean_absolute_error: 0.2373 - val_loss: 0.0404 - val_mean_absolute_error: 0.1701
Epoch 3/50
150/150 [==============================] - 1s 9ms/step - loss: 0.0856 - mean_absolute_error: 0.2342 - val_loss: 0.0380 - val_mean_absolute_error: 0.1641
Epoch 4/50
150/150 [==============================] - 1s 10ms/step - loss: 0.0838 - mean_absolute_error: 0.2336 - val_loss: 0.0411 - val_mean_absolute_error: 0.1736
Epoch 5/50
150/150 [==============================] - 2s 12ms/step - loss: 0.0839 - mean_absolute_error: 0.2325 - val_loss: 0.0404 - val_mean_absolute_error: 0.1709
Epoch 6/50
150/150 [==============================] - 2s 11ms/step - loss: 0.0828 - mean_absolute_error: 0.2289 - val_loss: 0.0389 - val_mean_absolute_error: 0.1665
Epoch 7/50


In [ ]:
scores=model.evaluate_generator(test_generator, verbose=0)

<ipython-input-170-ac2a51eb67e8>:1: UserWarning: `Model.evaluate_generator` is deprecated and will be removed in a future version. Please use `Model.evaluate`, which supports generators.
  scores=model.evaluate_generator(test_generator, verbose=0)


In [ ]:
print('MSE: %.4f' % scores[0])
print('RME: %.4f' % scores[1])


MSE: 0.1118
RME: 0.2704


In [ ]:
predictions=model.predict_generator(test_generator)

<ipython-input-163-6ca49477046f>:1: UserWarning: `Model.predict_generator` is deprecated and will be removed in a future version. Please use `Model.predict`, which supports generators.
  predictions=model.predict_generator(test_generator)


In [ ]:
predictions.shape[0]

34

In [ ]:
predictions

array([[0.34309343],
       [0.1819797 ],
       [0.55876714],
       [0.7366869 ],
       [0.4567951 ],
       [0.6806617 ],
       [0.18325263],
       [0.5497718 ],
       [0.7211465 ],
       [1.0629303 ],
       [0.66443753],
       [0.33483422],
       [0.1235183 ],
       [0.06838651],
       [0.8383053 ],
       [0.9920355 ],
       [0.2625771 ],
       [0.12151825],
       [0.2318232 ],
       [0.5855776 ],
       [0.3323176 ],
       [0.45723847],
       [0.35475177],
       [0.46648154],
       [0.49803042],
       [0.5117681 ],
       [0.14491749],
       [0.5459828 ],
       [0.4565252 ],
       [0.62219924],
       [0.27845448],
       [0.4865439 ],
       [0.22427748],
       [0.37831053]], dtype=float32)

In [ ]:
y_test

array([0.15768463, 0.13772455, 0.0758483 , 0.28343314, 0.24750499,
       0.18163673, 0.23952096, 0.0738523 , 0.78043912, 0.13173653,
       0.45309381, 0.38123752, 0.61876248, 0.34131737, 0.27145709,
       0.28143713, 0.07185629, 0.48103792, 0.11377246, 0.30139721,
       0.23153693, 0.18163673, 0.19560878, 0.48502994, 0.28143713,
       0.30139721, 0.32934133, 0.16966068, 0.249501  , 0.24151697,
       0.36526944, 0.15568862, 0.0259481 , 0.18363273, 0.08183633,
       0.09381238, 0.02794411, 0.09181637, 0.06586826])

## deneme 

In [ ]:
# splitting the data 
target=df["_field_mag"].tolist()

In [ ]:
target[0:11]

[1.12, 1.9, 4.7, 1.4, 0.98, 0.88, 1.33, 1.1, 5.0, 1.8, 1.8]

In [ ]:
features=df[[ '_field_mag','_field_cdi', '_field_depth', '_field_dmin', '_field_felt',
       '_field_gap', '_field_lat', '_field_lon', '_field_mmi',
       '_field_nst', '_field_rms', '_field_sig', '_field_tsunami',
       'magType_mb', 'magType_mb_lg', 'magType_md', 'magType_ml',
       'magType_mwr', 'magType_mww', 'net_ak', 'net_ci', 'net_hv', 'net_nc',
       'net_ok', 'net_pr', 'net_us']].to_numpy().tolist()   #it has more dimension so firstly i need to convert to numpy array the to_list.

In [ ]:
features[0:11][0]  #bir deprem icin 26 tane yani kolon sayısı kadar değer var yani ok oldu.

[1.12,
 0.0,
 29.53,
 0.01774,
 0.0,
 186.0,
 38.8236656,
 -122.8123322,
 0.0,
 7.0,
 0.24,
 19.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0]

In [ ]:
ts_generator=TimeseriesGenerator(data= features, targets=target,length=5,sampling_rate=1,batch_size =1, stride=1)
                                                                       
                    #sampling rate is 1 because we want to continous value,next value next value... 
                    #batch_size degistirebilrim


In [ ]:
ts_generator[0] # it is the first batch
#ilk 5'ini verip 8.80'i tahmin etmeye calıscam

(array([[[ 1.12000000e+00,  0.00000000e+00,  2.95300000e+01,
           1.77400000e-02,  0.00000000e+00,  1.86000000e+02,
           3.88236656e+01, -1.22812332e+02,  0.00000000e+00,
           7.00000000e+00,  2.40000000e-01,  1.90000000e+01,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00],
         [ 1.90000000e+00,  0.00000000e+00,  7.50000000e+01,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           5.91826000e+01, -1.53193000e+02,  0.00000000e+00,
           0.00000000e+00,  3.10000000e-01,  5.60000000e+01,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+

In [ ]:
ts_generator[1] #second batch, it is skip the first column and move 

(array([[[ 1.90000000e+00,  0.00000000e+00,  7.50000000e+01,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           5.91826000e+01, -1.53193000e+02,  0.00000000e+00,
           0.00000000e+00,  3.10000000e-01,  5.60000000e+01,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00],
         [ 4.70000000e+00,  0.00000000e+00,  1.00000000e+01,
           7.51900000e+00,  0.00000000e+00,  6.00000000e+01,
          -1.27679000e+01,  6.63649000e+01,  0.00000000e+00,
           6.30000000e+01,  3.70000000e-01,  3.40000000e+02,
           0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+

In [ ]:
len(ts_generator)

189

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 194 entries, 0 to 193
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   _field_cdi      194 non-null    float64
 1   _field_depth    194 non-null    float64
 2   _field_dmin     194 non-null    float64
 3   _field_felt     194 non-null    int64  
 4   _field_gap      194 non-null    float64
 5   _field_lat      194 non-null    float64
 6   _field_lon      194 non-null    float64
 7   _field_mag      194 non-null    float64
 8   _field_mmi      194 non-null    float64
 9   _field_nst      194 non-null    int64  
 10  _field_rms      194 non-null    float64
 11  _field_sig      194 non-null    int64  
 12  _field_tsunami  194 non-null    int64  
 13  magType_mb      194 non-null    int64  
 14  magType_mb_lg   194 non-null    int64  
 15  magType_md      194 non-null    int64  
 16  magType_ml      194 non-null    int64  
 17  magType_mwr     194 non-null    int

In [ ]:
df[["_field_mag"]].describe() #max ve min arasında cok var,standart scaler or min max scaler mı yapsam..
                              # min max yapacagım cünkü 5lik bir depremle 0.2lik arasında büyük fark var,
                              # bu veri deprem verisi oldugundan fark ediyor küçük değerler bile.

_field_mag
count  194.000000
mean     1.948299
std      1.346885
min      0.290000
25%      1.052500
50%      1.500000
75%      2.357500
max      5.300000

In [ ]:
scaler=MinMaxScaler()

In [ ]:
scaled_df= scaler.fit_transform()

In [ ]:
"""def windowed_dataset(series, window_size=G.WINDOW_SIZE, batch_size=G.BATCH_SIZE, shuffle_buffer=G.SHUFFLE_BUFFER_SIZE):
    
  
    
    # Create dataset from the series
    dataset = tf.data.Dataset.from_tensor_slices(series)
    
    # Slice the dataset into the appropriate windows
    dataset = dataset.window(window_size+1, shift=1, drop_remainder=True)
    
    # Flatten the dataset
    dataset = dataset.flat_map(lambda window: window.batch(window_size+1))
    
    # Shuffle it
    dataset = dataset.shuffle(shuffle_buffer)
    
    # Split it into the features and labels
    dataset = dataset.map(lambda window: (window[:-1], window[-1]))
    
    # Batch it
    dataset = dataset.batch(batch_size).prefetch(1)
    
    
    return dataset"""

In [ ]:
##  creating windowed dataset



In [ ]:
"""def windowed_dataset(series, window_size=G.WINDOW_SIZE, batch_size=G.BATCH_SIZE, shuffle_buffer=G.SHUFFLE_BUFFER_SIZE):

    
    # Create dataset from the series
    dataset = tf.data.Dataset.from_tensor_slices(series)
    
    # Slice the dataset into the appropriate windows
    dataset = dataset.window(window_size+1, shift=1, drop_remainder=True)
    
    # Flatten the dataset
    dataset = dataset.flat_map(lambda window: window.batch(window_size+1))
    
    # Shuffle it
    dataset = dataset.shuffle(shuffle_buffer)
    
    # Split it into the features and labels
    dataset = dataset.map(lambda window: (window[:-1], window[-1]))
    
    # Batch it
    dataset = dataset.batch(batch_size).prefetch(1)
    
    return dataset"""